import Head from "next/head";
import Link from "next/link";
import { useSelector } from "react-redux";
import {
  Container,
  Divider,
  Loader,
  Menu,
  Dropdown,
  Message,
} from "semantic-ui-react";

import ProductList from "../src/components/ProductList";
import {
  useGetAllProductsQuery,
  useGetMenuQuery,
} from "../src/services/product";
import { selectCount } from "../src/slices/basketSlice";

export default function Home() {
  const products = useGetAllProductsQuery();
  const menus = useGetMenuQuery();

  const basketCount = useSelector(selectCount);

  if (products.isLoading || menus.isLoading) {
    return (
      <Loader active inline="centered">
        Loading
      </Loader>
    );
  }

  if (products.isError || menus.isError) {
    return (
      <Message negative>
        <Message.Header>
          We're currently experiencing some technical difficulties.
        </Message.Header>
        <p>Please try again later</p>
      </Message>
    );
  }

  return (
    <div>
      <Head>
        <title>PLT Test app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* This nav can be extracted to a separate component */}
      <nav>
        <Menu stackable>
          <Menu.Item>
            <p>PRETTYLITTLETHING</p>
          </Menu.Item>

          <Menu.Item>
            <Link href="/basket">Basket ({basketCount})</Link>
          </Menu.Item>
          {menus.data?.map((category) =>
            category.children.map((child) => (
              <Dropdown
                key={child.name}
                text={child.name}
                pointing
                className="link item"
              >
                <Dropdown.Menu>
                  {child.categories.map((subItem) => (
                    <Dropdown.Item key={subItem}>{subItem}</Dropdown.Item>
                  ))}
                </Dropdown.Menu>
              </Dropdown>
            ))
          )}
        </Menu>
      </nav>
      <Divider hidden />
      <Container>
        <main>
          <ProductList data={products.data || []} />
        </main>
      </Container>
    </div>
  );
}
